/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toy.anagrams.ui;

/**
 *
 * @author Roland
 */
public class BoardPane extends javax.swing.JPanel {

    /**
     * Creates new form BoardLayout
     */
    public BoardPane() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letra01 = new javax.swing.JLabel();
        letra2 = new javax.swing.JLabel();
        letra3 = new javax.swing.JLabel();
        letra4 = new javax.swing.JLabel();
        letra5 = new javax.swing.JLabel();
        letra6 = new javax.swing.JLabel();
        letra7 = new javax.swing.JLabel();
        letra8 = new javax.swing.JLabel();
        letra9 = new javax.swing.JLabel();
        letra10 = new javax.swing.JLabel();
        letra11 = new javax.swing.JLabel();
        letra12 = new javax.swing.JLabel();
        letra13 = new javax.swing.JLabel();
        letra14 = new javax.swing.JLabel();
        letra15 = new javax.swing.JLabel();
        letra16 = new javax.swing.JLabel();
        letra17 = new javax.swing.JLabel();
        letra18 = new javax.swing.JLabel();
        letra19 = new javax.swing.JLabel();
        letra20 = new javax.swing.JLabel();
        letra21 = new javax.swing.JLabel();
        letra22 = new javax.swing.JLabel();
        letra23 = new javax.swing.JLabel();
        letra24 = new javax.swing.JLabel();
        letra25 = new javax.swing.JLabel();
        letra26 = new javax.swing.JLabel();
        letra27 = new javax.swing.JLabel();
        letra28 = new javax.swing.JLabel();
        letra29 = new javax.swing.JLabel();
        letra30 = new javax.swing.JLabel();
        letra31 = new javax.swing.JLabel();
        letra32 = new javax.swing.JLabel();
        letra33 = new javax.swing.JLabel();
        letra34 = new javax.swing.JLabel();
        letra35 = new javax.swing.JLabel();
        letra36 = new javax.swing.JLabel();
        letra37 = new javax.swing.JLabel();
        letra38 = new javax.swing.JLabel();
        letra39 = new javax.swing.JLabel();
        letra40 = new javax.swing.JLabel();
        letra41 = new javax.swing.JLabel();
        letra42 = new javax.swing.JLabel();
        letra43 = new javax.swing.JLabel();
        letra44 = new javax.swing.JLabel();
        letra45 = new javax.swing.JLabel();
        letra46 = new javax.swing.JLabel();
        letra47 = new javax.swing.JLabel();
        letra48 = new javax.swing.JLabel();
        letra49 = new javax.swing.JLabel();
        letra50 = new javax.swing.JLabel();
        letra51 = new javax.swing.JLabel();
        letra52 = new javax.swing.JLabel();
        letra53 = new javax.swing.JLabel();
        letra54 = new javax.swing.JLabel();
        letra55 = new javax.swing.JLabel();
        letra56 = new javax.swing.JLabel();
        letra57 = new javax.swing.JLabel();
        letra58 = new javax.swing.JLabel();
        letra59 = new javax.swing.JLabel();
        letra60 = new javax.swing.JLabel();
        letra61 = new javax.swing.JLabel();
        letra62 = new javax.swing.JLabel();
        letra63 = new javax.swing.JLabel();
        letra64 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 128, 185));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setName("lb01"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new java.awt.GridLayout(8, 8, 10, 10));

        letra01.setBackground(new java.awt.Color(255, 255, 255));
        letra01.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra01.setForeground(new java.awt.Color(255, 255, 255));
        letra01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra01.setText("A");
        letra01.setAutoscrolls(true);
        letra01.setMaximumSize(new java.awt.Dimension(50, 50));
        letra01.setMinimumSize(new java.awt.Dimension(50, 50));
        letra01.setOpaque(true);
        letra01.setPreferredSize(new java.awt.Dimension(50, 50));
        letra01.setSize(new java.awt.Dimension(65, 46));
        add(letra01);

        letra2.setBackground(new java.awt.Color(255, 255, 255));
        letra2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra2.setForeground(new java.awt.Color(255, 255, 255));
        letra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra2.setText("A");
        letra2.setAutoscrolls(true);
        letra2.setMaximumSize(new java.awt.Dimension(50, 50));
        letra2.setMinimumSize(new java.awt.Dimension(50, 50));
        letra2.setOpaque(true);
        letra2.setPreferredSize(new java.awt.Dimension(50, 50));
        letra2.setSize(new java.awt.Dimension(65, 46));
        add(letra2);

        letra3.setBackground(new java.awt.Color(255, 255, 255));
        letra3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra3.setForeground(new java.awt.Color(255, 255, 255));
        letra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra3.setText("A");
        letra3.setAutoscrolls(true);
        letra3.setMaximumSize(new java.awt.Dimension(50, 50));
        letra3.setMinimumSize(new java.awt.Dimension(50, 50));
        letra3.setOpaque(true);
        letra3.setPreferredSize(new java.awt.Dimension(50, 50));
        letra3.setSize(new java.awt.Dimension(65, 46));
        add(letra3);

        letra4.setBackground(new java.awt.Color(255, 255, 255));
        letra4.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra4.setForeground(new java.awt.Color(255, 255, 255));
        letra4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra4.setText("A");
        letra4.setAutoscrolls(true);
        letra4.setMaximumSize(new java.awt.Dimension(50, 50));
        letra4.setMinimumSize(new java.awt.Dimension(50, 50));
        letra4.setOpaque(true);
        letra4.setPreferredSize(new java.awt.Dimension(50, 50));
        letra4.setSize(new java.awt.Dimension(65, 46));
        add(letra4);

        letra5.setBackground(new java.awt.Color(255, 255, 255));
        letra5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra5.setForeground(new java.awt.Color(255, 255, 255));
        letra5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra5.setText("A");
        letra5.setAutoscrolls(true);
        letra5.setMaximumSize(new java.awt.Dimension(50, 50));
        letra5.setMinimumSize(new java.awt.Dimension(50, 50));
        letra5.setOpaque(true);
        letra5.setPreferredSize(new java.awt.Dimension(50, 50));
        letra5.setSize(new java.awt.Dimension(65, 46));
        add(letra5);

        letra6.setBackground(new java.awt.Color(255, 255, 255));
        letra6.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra6.setForeground(new java.awt.Color(255, 255, 255));
        letra6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra6.setText("A");
        letra6.setAutoscrolls(true);
        letra6.setMaximumSize(new java.awt.Dimension(50, 50));
        letra6.setMinimumSize(new java.awt.Dimension(50, 50));
        letra6.setOpaque(true);
        letra6.setPreferredSize(new java.awt.Dimension(50, 50));
        letra6.setSize(new java.awt.Dimension(65, 46));
        add(letra6);

        letra7.setBackground(new java.awt.Color(255, 255, 255));
        letra7.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra7.setForeground(new java.awt.Color(255, 255, 255));
        letra7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra7.setText("A");
        letra7.setAutoscrolls(true);
        letra7.setMaximumSize(new java.awt.Dimension(50, 50));
        letra7.setMinimumSize(new java.awt.Dimension(50, 50));
        letra7.setOpaque(true);
        letra7.setPreferredSize(new java.awt.Dimension(50, 50));
        letra7.setSize(new java.awt.Dimension(65, 46));
        add(letra7);

        letra8.setBackground(new java.awt.Color(255, 255, 255));
        letra8.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra8.setForeground(new java.awt.Color(255, 255, 255));
        letra8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra8.setText("A");
        letra8.setAutoscrolls(true);
        letra8.setMaximumSize(new java.awt.Dimension(50, 50));
        letra8.setMinimumSize(new java.awt.Dimension(50, 50));
        letra8.setOpaque(true);
        letra8.setPreferredSize(new java.awt.Dimension(50, 50));
        letra8.setSize(new java.awt.Dimension(65, 46));
        add(letra8);

        letra9.setBackground(new java.awt.Color(255, 255, 255));
        letra9.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra9.setForeground(new java.awt.Color(255, 255, 255));
        letra9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra9.setText("A");
        letra9.setAutoscrolls(true);
        letra9.setMaximumSize(new java.awt.Dimension(50, 50));
        letra9.setMinimumSize(new java.awt.Dimension(50, 50));
        letra9.setOpaque(true);
        letra9.setPreferredSize(new java.awt.Dimension(50, 50));
        letra9.setSize(new java.awt.Dimension(65, 46));
        add(letra9);

        letra10.setBackground(new java.awt.Color(255, 255, 255));
        letra10.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra10.setForeground(new java.awt.Color(255, 255, 255));
        letra10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra10.setText("A");
        letra10.setAutoscrolls(true);
        letra10.setMaximumSize(new java.awt.Dimension(50, 50));
        letra10.setMinimumSize(new java.awt.Dimension(50, 50));
        letra10.setOpaque(true);
        letra10.setPreferredSize(new java.awt.Dimension(50, 50));
        letra10.setSize(new java.awt.Dimension(65, 46));
        add(letra10);

        letra11.setBackground(new java.awt.Color(255, 255, 255));
        letra11.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra11.setForeground(new java.awt.Color(255, 255, 255));
        letra11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra11.setText("A");
        letra11.setAutoscrolls(true);
        letra11.setMaximumSize(new java.awt.Dimension(50, 50));
        letra11.setMinimumSize(new java.awt.Dimension(50, 50));
        letra11.setOpaque(true);
        letra11.setPreferredSize(new java.awt.Dimension(50, 50));
        letra11.setSize(new java.awt.Dimension(65, 46));
        add(letra11);

        letra12.setBackground(new java.awt.Color(255, 255, 255));
        letra12.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra12.setForeground(new java.awt.Color(255, 255, 255));
        letra12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra12.setText("A");
        letra12.setAutoscrolls(true);
        letra12.setMaximumSize(new java.awt.Dimension(50, 50));
        letra12.setMinimumSize(new java.awt.Dimension(50, 50));
        letra12.setOpaque(true);
        letra12.setPreferredSize(new java.awt.Dimension(50, 50));
        letra12.setSize(new java.awt.Dimension(65, 46));
        add(letra12);

        letra13.setBackground(new java.awt.Color(255, 255, 255));
        letra13.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra13.setForeground(new java.awt.Color(255, 255, 255));
        letra13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra13.setText("A");
        letra13.setAutoscrolls(true);
        letra13.setMaximumSize(new java.awt.Dimension(50, 50));
        letra13.setMinimumSize(new java.awt.Dimension(50, 50));
        letra13.setOpaque(true);
        letra13.setPreferredSize(new java.awt.Dimension(50, 50));
        letra13.setSize(new java.awt.Dimension(65, 46));
        add(letra13);

        letra14.setBackground(new java.awt.Color(255, 255, 255));
        letra14.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra14.setForeground(new java.awt.Color(255, 255, 255));
        letra14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra14.setText("A");
        letra14.setAutoscrolls(true);
        letra14.setMaximumSize(new java.awt.Dimension(50, 50));
        letra14.setMinimumSize(new java.awt.Dimension(50, 50));
        letra14.setOpaque(true);
        letra14.setPreferredSize(new java.awt.Dimension(50, 50));
        letra14.setSize(new java.awt.Dimension(65, 46));
        add(letra14);

        letra15.setBackground(new java.awt.Color(255, 255, 255));
        letra15.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra15.setForeground(new java.awt.Color(255, 255, 255));
        letra15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra15.setText("A");
        letra15.setAutoscrolls(true);
        letra15.setMaximumSize(new java.awt.Dimension(50, 50));
        letra15.setMinimumSize(new java.awt.Dimension(50, 50));
        letra15.setOpaque(true);
        letra15.setPreferredSize(new java.awt.Dimension(50, 50));
        letra15.setSize(new java.awt.Dimension(65, 46));
        add(letra15);

        letra16.setBackground(new java.awt.Color(255, 255, 255));
        letra16.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra16.setForeground(new java.awt.Color(255, 255, 255));
        letra16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra16.setText("A");
        letra16.setAutoscrolls(true);
        letra16.setMaximumSize(new java.awt.Dimension(50, 50));
        letra16.setMinimumSize(new java.awt.Dimension(50, 50));
        letra16.setOpaque(true);
        letra16.setPreferredSize(new java.awt.Dimension(50, 50));
        letra16.setSize(new java.awt.Dimension(65, 46));
        add(letra16);

        letra17.setBackground(new java.awt.Color(255, 255, 255));
        letra17.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra17.setForeground(new java.awt.Color(255, 255, 255));
        letra17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra17.setText("A");
        letra17.setAutoscrolls(true);
        letra17.setMaximumSize(new java.awt.Dimension(50, 50));
        letra17.setMinimumSize(new java.awt.Dimension(50, 50));
        letra17.setOpaque(true);
        letra17.setPreferredSize(new java.awt.Dimension(50, 50));
        letra17.setSize(new java.awt.Dimension(65, 46));
        add(letra17);

        letra18.setBackground(new java.awt.Color(255, 255, 255));
        letra18.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra18.setForeground(new java.awt.Color(255, 255, 255));
        letra18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra18.setText("A");
        letra18.setAutoscrolls(true);
        letra18.setMaximumSize(new java.awt.Dimension(50, 50));
        letra18.setMinimumSize(new java.awt.Dimension(50, 50));
        letra18.setOpaque(true);
        letra18.setPreferredSize(new java.awt.Dimension(50, 50));
        letra18.setSize(new java.awt.Dimension(65, 46));
        add(letra18);

        letra19.setBackground(new java.awt.Color(255, 255, 255));
        letra19.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra19.setForeground(new java.awt.Color(255, 255, 255));
        letra19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra19.setText("A");
        letra19.setAutoscrolls(true);
        letra19.setMaximumSize(new java.awt.Dimension(50, 50));
        letra19.setMinimumSize(new java.awt.Dimension(50, 50));
        letra19.setOpaque(true);
        letra19.setPreferredSize(new java.awt.Dimension(50, 50));
        letra19.setSize(new java.awt.Dimension(65, 46));
        add(letra19);

        letra20.setBackground(new java.awt.Color(255, 255, 255));
        letra20.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra20.setForeground(new java.awt.Color(255, 255, 255));
        letra20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra20.setText("A");
        letra20.setAutoscrolls(true);
        letra20.setMaximumSize(new java.awt.Dimension(50, 50));
        letra20.setMinimumSize(new java.awt.Dimension(50, 50));
        letra20.setOpaque(true);
        letra20.setPreferredSize(new java.awt.Dimension(50, 50));
        letra20.setSize(new java.awt.Dimension(65, 46));
        add(letra20);

        letra21.setBackground(new java.awt.Color(255, 255, 255));
        letra21.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra21.setForeground(new java.awt.Color(255, 255, 255));
        letra21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra21.setText("A");
        letra21.setAutoscrolls(true);
        letra21.setMaximumSize(new java.awt.Dimension(50, 50));
        letra21.setMinimumSize(new java.awt.Dimension(50, 50));
        letra21.setOpaque(true);
        letra21.setPreferredSize(new java.awt.Dimension(50, 50));
        letra21.setSize(new java.awt.Dimension(65, 46));
        add(letra21);

        letra22.setBackground(new java.awt.Color(255, 255, 255));
        letra22.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra22.setForeground(new java.awt.Color(255, 255, 255));
        letra22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra22.setText("A");
        letra22.setAutoscrolls(true);
        letra22.setMaximumSize(new java.awt.Dimension(50, 50));
        letra22.setMinimumSize(new java.awt.Dimension(50, 50));
        letra22.setOpaque(true);
        letra22.setPreferredSize(new java.awt.Dimension(50, 50));
        letra22.setSize(new java.awt.Dimension(65, 46));
        add(letra22);

        letra23.setBackground(new java.awt.Color(255, 255, 255));
        letra23.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra23.setForeground(new java.awt.Color(255, 255, 255));
        letra23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra23.setText("A");
        letra23.setAutoscrolls(true);
        letra23.setMaximumSize(new java.awt.Dimension(50, 50));
        letra23.setMinimumSize(new java.awt.Dimension(50, 50));
        letra23.setOpaque(true);
        letra23.setPreferredSize(new java.awt.Dimension(50, 50));
        letra23.setSize(new java.awt.Dimension(65, 46));
        add(letra23);

        letra24.setBackground(new java.awt.Color(255, 255, 255));
        letra24.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra24.setForeground(new java.awt.Color(255, 255, 255));
        letra24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra24.setText("A");
        letra24.setAutoscrolls(true);
        letra24.setMaximumSize(new java.awt.Dimension(50, 50));
        letra24.setMinimumSize(new java.awt.Dimension(50, 50));
        letra24.setOpaque(true);
        letra24.setPreferredSize(new java.awt.Dimension(50, 50));
        letra24.setSize(new java.awt.Dimension(65, 46));
        add(letra24);

        letra25.setBackground(new java.awt.Color(255, 255, 255));
        letra25.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra25.setForeground(new java.awt.Color(255, 255, 255));
        letra25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra25.setText("A");
        letra25.setAutoscrolls(true);
        letra25.setMaximumSize(new java.awt.Dimension(50, 50));
        letra25.setMinimumSize(new java.awt.Dimension(50, 50));
        letra25.setOpaque(true);
        letra25.setPreferredSize(new java.awt.Dimension(50, 50));
        letra25.setSize(new java.awt.Dimension(65, 46));
        add(letra25);

        letra26.setBackground(new java.awt.Color(255, 255, 255));
        letra26.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra26.setForeground(new java.awt.Color(255, 255, 255));
        letra26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra26.setText("A");
        letra26.setAutoscrolls(true);
        letra26.setMaximumSize(new java.awt.Dimension(50, 50));
        letra26.setMinimumSize(new java.awt.Dimension(50, 50));
        letra26.setOpaque(true);
        letra26.setPreferredSize(new java.awt.Dimension(50, 50));
        letra26.setSize(new java.awt.Dimension(65, 46));
        add(letra26);

        letra27.setBackground(new java.awt.Color(255, 255, 255));
        letra27.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra27.setForeground(new java.awt.Color(255, 255, 255));
        letra27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra27.setText("A");
        letra27.setAutoscrolls(true);
        letra27.setMaximumSize(new java.awt.Dimension(50, 50));
        letra27.setMinimumSize(new java.awt.Dimension(50, 50));
        letra27.setOpaque(true);
        letra27.setPreferredSize(new java.awt.Dimension(50, 50));
        letra27.setSize(new java.awt.Dimension(65, 46));
        add(letra27);

        letra28.setBackground(new java.awt.Color(255, 255, 255));
        letra28.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra28.setForeground(new java.awt.Color(255, 255, 255));
        letra28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra28.setText("A");
        letra28.setAutoscrolls(true);
        letra28.setMaximumSize(new java.awt.Dimension(50, 50));
        letra28.setMinimumSize(new java.awt.Dimension(50, 50));
        letra28.setOpaque(true);
        letra28.setPreferredSize(new java.awt.Dimension(50, 50));
        letra28.setSize(new java.awt.Dimension(65, 46));
        add(letra28);

        letra29.setBackground(new java.awt.Color(255, 255, 255));
        letra29.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra29.setForeground(new java.awt.Color(255, 255, 255));
        letra29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra29.setText("A");
        letra29.setAutoscrolls(true);
        letra29.setMaximumSize(new java.awt.Dimension(50, 50));
        letra29.setMinimumSize(new java.awt.Dimension(50, 50));
        letra29.setOpaque(true);
        letra29.setPreferredSize(new java.awt.Dimension(50, 50));
        letra29.setSize(new java.awt.Dimension(65, 46));
        add(letra29);

        letra30.setBackground(new java.awt.Color(255, 255, 255));
        letra30.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra30.setForeground(new java.awt.Color(255, 255, 255));
        letra30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra30.setText("A");
        letra30.setAutoscrolls(true);
        letra30.setMaximumSize(new java.awt.Dimension(50, 50));
        letra30.setMinimumSize(new java.awt.Dimension(50, 50));
        letra30.setOpaque(true);
        letra30.setPreferredSize(new java.awt.Dimension(50, 50));
        letra30.setSize(new java.awt.Dimension(65, 46));
        add(letra30);

        letra31.setBackground(new java.awt.Color(255, 255, 255));
        letra31.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra31.setForeground(new java.awt.Color(255, 255, 255));
        letra31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra31.setText("A");
        letra31.setAutoscrolls(true);
        letra31.setMaximumSize(new java.awt.Dimension(50, 50));
        letra31.setMinimumSize(new java.awt.Dimension(50, 50));
        letra31.setOpaque(true);
        letra31.setPreferredSize(new java.awt.Dimension(50, 50));
        letra31.setSize(new java.awt.Dimension(65, 46));
        add(letra31);

        letra32.setBackground(new java.awt.Color(255, 255, 255));
        letra32.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra32.setForeground(new java.awt.Color(255, 255, 255));
        letra32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra32.setText("A");
        letra32.setAutoscrolls(true);
        letra32.setMaximumSize(new java.awt.Dimension(50, 50));
        letra32.setMinimumSize(new java.awt.Dimension(50, 50));
        letra32.setOpaque(true);
        letra32.setPreferredSize(new java.awt.Dimension(50, 50));
        letra32.setSize(new java.awt.Dimension(65, 46));
        add(letra32);

        letra33.setBackground(new java.awt.Color(255, 255, 255));
        letra33.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra33.setForeground(new java.awt.Color(255, 255, 255));
        letra33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra33.setText("A");
        letra33.setAutoscrolls(true);
        letra33.setMaximumSize(new java.awt.Dimension(50, 50));
        letra33.setMinimumSize(new java.awt.Dimension(50, 50));
        letra33.setOpaque(true);
        letra33.setPreferredSize(new java.awt.Dimension(50, 50));
        letra33.setSize(new java.awt.Dimension(65, 46));
        add(letra33);

        letra34.setBackground(new java.awt.Color(255, 255, 255));
        letra34.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra34.setForeground(new java.awt.Color(255, 255, 255));
        letra34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra34.setText("A");
        letra34.setAutoscrolls(true);
        letra34.setMaximumSize(new java.awt.Dimension(50, 50));
        letra34.setMinimumSize(new java.awt.Dimension(50, 50));
        letra34.setOpaque(true);
        letra34.setPreferredSize(new java.awt.Dimension(50, 50));
        letra34.setSize(new java.awt.Dimension(65, 46));
        add(letra34);

        letra35.setBackground(new java.awt.Color(255, 255, 255));
        letra35.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra35.setForeground(new java.awt.Color(255, 255, 255));
        letra35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra35.setText("A");
        letra35.setAutoscrolls(true);
        letra35.setMaximumSize(new java.awt.Dimension(50, 50));
        letra35.setMinimumSize(new java.awt.Dimension(50, 50));
        letra35.setOpaque(true);
        letra35.setPreferredSize(new java.awt.Dimension(50, 50));
        letra35.setSize(new java.awt.Dimension(65, 46));
        add(letra35);

        letra36.setBackground(new java.awt.Color(255, 255, 255));
        letra36.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra36.setForeground(new java.awt.Color(255, 255, 255));
        letra36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra36.setText("A");
        letra36.setAutoscrolls(true);
        letra36.setMaximumSize(new java.awt.Dimension(50, 50));
        letra36.setMinimumSize(new java.awt.Dimension(50, 50));
        letra36.setOpaque(true);
        letra36.setPreferredSize(new java.awt.Dimension(50, 50));
        letra36.setSize(new java.awt.Dimension(65, 46));
        add(letra36);

        letra37.setBackground(new java.awt.Color(255, 255, 255));
        letra37.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra37.setForeground(new java.awt.Color(255, 255, 255));
        letra37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra37.setText("A");
        letra37.setAutoscrolls(true);
        letra37.setMaximumSize(new java.awt.Dimension(50, 50));
        letra37.setMinimumSize(new java.awt.Dimension(50, 50));
        letra37.setOpaque(true);
        letra37.setPreferredSize(new java.awt.Dimension(50, 50));
        letra37.setSize(new java.awt.Dimension(65, 46));
        add(letra37);

        letra38.setBackground(new java.awt.Color(255, 255, 255));
        letra38.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra38.setForeground(new java.awt.Color(255, 255, 255));
        letra38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra38.setText("A");
        letra38.setAutoscrolls(true);
        letra38.setMaximumSize(new java.awt.Dimension(50, 50));
        letra38.setMinimumSize(new java.awt.Dimension(50, 50));
        letra38.setOpaque(true);
        letra38.setPreferredSize(new java.awt.Dimension(50, 50));
        letra38.setSize(new java.awt.Dimension(65, 46));
        add(letra38);

        letra39.setBackground(new java.awt.Color(255, 255, 255));
        letra39.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra39.setForeground(new java.awt.Color(255, 255, 255));
        letra39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra39.setText("A");
        letra39.setAutoscrolls(true);
        letra39.setMaximumSize(new java.awt.Dimension(50, 50));
        letra39.setMinimumSize(new java.awt.Dimension(50, 50));
        letra39.setOpaque(true);
        letra39.setPreferredSize(new java.awt.Dimension(50, 50));
        letra39.setSize(new java.awt.Dimension(65, 46));
        add(letra39);

        letra40.setBackground(new java.awt.Color(255, 255, 255));
        letra40.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra40.setForeground(new java.awt.Color(255, 255, 255));
        letra40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra40.setText("A");
        letra40.setAutoscrolls(true);
        letra40.setMaximumSize(new java.awt.Dimension(50, 50));
        letra40.setMinimumSize(new java.awt.Dimension(50, 50));
        letra40.setOpaque(true);
        letra40.setPreferredSize(new java.awt.Dimension(50, 50));
        letra40.setSize(new java.awt.Dimension(65, 46));
        add(letra40);

        letra41.setBackground(new java.awt.Color(255, 255, 255));
        letra41.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra41.setForeground(new java.awt.Color(255, 255, 255));
        letra41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra41.setText("A");
        letra41.setAutoscrolls(true);
        letra41.setMaximumSize(new java.awt.Dimension(50, 50));
        letra41.setMinimumSize(new java.awt.Dimension(50, 50));
        letra41.setOpaque(true);
        letra41.setPreferredSize(new java.awt.Dimension(50, 50));
        letra41.setSize(new java.awt.Dimension(65, 46));
        add(letra41);

        letra42.setBackground(new java.awt.Color(255, 255, 255));
        letra42.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra42.setForeground(new java.awt.Color(255, 255, 255));
        letra42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra42.setText("A");
        letra42.setAutoscrolls(true);
        letra42.setMaximumSize(new java.awt.Dimension(50, 50));
        letra42.setMinimumSize(new java.awt.Dimension(50, 50));
        letra42.setOpaque(true);
        letra42.setPreferredSize(new java.awt.Dimension(50, 50));
        letra42.setSize(new java.awt.Dimension(65, 46));
        add(letra42);

        letra43.setBackground(new java.awt.Color(255, 255, 255));
        letra43.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra43.setForeground(new java.awt.Color(255, 255, 255));
        letra43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra43.setText("Qu");
        letra43.setAutoscrolls(true);
        letra43.setMaximumSize(new java.awt.Dimension(50, 50));
        letra43.setMinimumSize(new java.awt.Dimension(50, 50));
        letra43.setOpaque(true);
        letra43.setPreferredSize(new java.awt.Dimension(50, 50));
        letra43.setSize(new java.awt.Dimension(65, 46));
        add(letra43);

        letra44.setBackground(new java.awt.Color(255, 255, 255));
        letra44.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra44.setForeground(new java.awt.Color(255, 255, 255));
        letra44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra44.setText("A");
        letra44.setAutoscrolls(true);
        letra44.setMaximumSize(new java.awt.Dimension(50, 50));
        letra44.setMinimumSize(new java.awt.Dimension(50, 50));
        letra44.setOpaque(true);
        letra44.setPreferredSize(new java.awt.Dimension(50, 50));
        letra44.setSize(new java.awt.Dimension(65, 46));
        add(letra44);

        letra45.setBackground(new java.awt.Color(255, 255, 255));
        letra45.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra45.setForeground(new java.awt.Color(255, 255, 255));
        letra45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra45.setText("A");
        letra45.setAutoscrolls(true);
        letra45.setMaximumSize(new java.awt.Dimension(50, 50));
        letra45.setMinimumSize(new java.awt.Dimension(50, 50));
        letra45.setOpaque(true);
        letra45.setPreferredSize(new java.awt.Dimension(50, 50));
        letra45.setSize(new java.awt.Dimension(65, 46));
        add(letra45);

        letra46.setBackground(new java.awt.Color(255, 255, 255));
        letra46.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra46.setForeground(new java.awt.Color(255, 255, 255));
        letra46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra46.setText("A");
        letra46.setAutoscrolls(true);
        letra46.setMaximumSize(new java.awt.Dimension(50, 50));
        letra46.setMinimumSize(new java.awt.Dimension(50, 50));
        letra46.setOpaque(true);
        letra46.setPreferredSize(new java.awt.Dimension(50, 50));
        letra46.setSize(new java.awt.Dimension(65, 46));
        add(letra46);

        letra47.setBackground(new java.awt.Color(255, 255, 255));
        letra47.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra47.setForeground(new java.awt.Color(255, 255, 255));
        letra47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra47.setText("A");
        letra47.setAutoscrolls(true);
        letra47.setMaximumSize(new java.awt.Dimension(50, 50));
        letra47.setMinimumSize(new java.awt.Dimension(50, 50));
        letra47.setOpaque(true);
        letra47.setPreferredSize(new java.awt.Dimension(50, 50));
        letra47.setSize(new java.awt.Dimension(65, 46));
        add(letra47);

        letra48.setBackground(new java.awt.Color(255, 255, 255));
        letra48.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra48.setForeground(new java.awt.Color(255, 255, 255));
        letra48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra48.setText("A");
        letra48.setAutoscrolls(true);
        letra48.setMaximumSize(new java.awt.Dimension(50, 50));
        letra48.setMinimumSize(new java.awt.Dimension(50, 50));
        letra48.setOpaque(true);
        letra48.setPreferredSize(new java.awt.Dimension(50, 50));
        letra48.setSize(new java.awt.Dimension(65, 46));
        add(letra48);

        letra49.setBackground(new java.awt.Color(255, 255, 255));
        letra49.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra49.setForeground(new java.awt.Color(255, 255, 255));
        letra49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra49.setText("A");
        letra49.setAutoscrolls(true);
        letra49.setMaximumSize(new java.awt.Dimension(50, 50));
        letra49.setMinimumSize(new java.awt.Dimension(50, 50));
        letra49.setOpaque(true);
        letra49.setPreferredSize(new java.awt.Dimension(50, 50));
        letra49.setSize(new java.awt.Dimension(65, 46));
        add(letra49);

        letra50.setBackground(new java.awt.Color(255, 255, 255));
        letra50.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra50.setForeground(new java.awt.Color(255, 255, 255));
        letra50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra50.setText("A");
        letra50.setAutoscrolls(true);
        letra50.setMaximumSize(new java.awt.Dimension(50, 50));
        letra50.setMinimumSize(new java.awt.Dimension(50, 50));
        letra50.setOpaque(true);
        letra50.setPreferredSize(new java.awt.Dimension(50, 50));
        letra50.setSize(new java.awt.Dimension(65, 46));
        add(letra50);

        letra51.setBackground(new java.awt.Color(255, 255, 255));
        letra51.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra51.setForeground(new java.awt.Color(255, 255, 255));
        letra51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra51.setText("A");
        letra51.setAutoscrolls(true);
        letra51.setMaximumSize(new java.awt.Dimension(50, 50));
        letra51.setMinimumSize(new java.awt.Dimension(50, 50));
        letra51.setOpaque(true);
        letra51.setPreferredSize(new java.awt.Dimension(50, 50));
        letra51.setSize(new java.awt.Dimension(65, 46));
        add(letra51);

        letra52.setBackground(new java.awt.Color(255, 255, 255));
        letra52.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra52.setForeground(new java.awt.Color(255, 255, 255));
        letra52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra52.setText("A");
        letra52.setAutoscrolls(true);
        letra52.setMaximumSize(new java.awt.Dimension(50, 50));
        letra52.setMinimumSize(new java.awt.Dimension(50, 50));
        letra52.setOpaque(true);
        letra52.setPreferredSize(new java.awt.Dimension(50, 50));
        letra52.setSize(new java.awt.Dimension(65, 46));
        add(letra52);

        letra53.setBackground(new java.awt.Color(255, 255, 255));
        letra53.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra53.setForeground(new java.awt.Color(255, 255, 255));
        letra53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra53.setText("A");
        letra53.setAutoscrolls(true);
        letra53.setMaximumSize(new java.awt.Dimension(50, 50));
        letra53.setMinimumSize(new java.awt.Dimension(50, 50));
        letra53.setOpaque(true);
        letra53.setPreferredSize(new java.awt.Dimension(50, 50));
        letra53.setSize(new java.awt.Dimension(65, 46));
        add(letra53);

        letra54.setBackground(new java.awt.Color(255, 255, 255));
        letra54.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra54.setForeground(new java.awt.Color(255, 255, 255));
        letra54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra54.setText("A");
        letra54.setAutoscrolls(true);
        letra54.setMaximumSize(new java.awt.Dimension(50, 50));
        letra54.setMinimumSize(new java.awt.Dimension(50, 50));
        letra54.setOpaque(true);
        letra54.setPreferredSize(new java.awt.Dimension(50, 50));
        letra54.setSize(new java.awt.Dimension(65, 46));
        add(letra54);

        letra55.setBackground(new java.awt.Color(255, 255, 255));
        letra55.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra55.setForeground(new java.awt.Color(255, 255, 255));
        letra55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra55.setText("A");
        letra55.setAutoscrolls(true);
        letra55.setMaximumSize(new java.awt.Dimension(50, 50));
        letra55.setMinimumSize(new java.awt.Dimension(50, 50));
        letra55.setOpaque(true);
        letra55.setPreferredSize(new java.awt.Dimension(50, 50));
        letra55.setSize(new java.awt.Dimension(65, 46));
        add(letra55);

        letra56.setBackground(new java.awt.Color(255, 255, 255));
        letra56.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra56.setForeground(new java.awt.Color(255, 255, 255));
        letra56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra56.setText("A");
        letra56.setAutoscrolls(true);
        letra56.setMaximumSize(new java.awt.Dimension(50, 50));
        letra56.setMinimumSize(new java.awt.Dimension(50, 50));
        letra56.setOpaque(true);
        letra56.setPreferredSize(new java.awt.Dimension(50, 50));
        letra56.setSize(new java.awt.Dimension(65, 46));
        add(letra56);

        letra57.setBackground(new java.awt.Color(255, 255, 255));
        letra57.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra57.setForeground(new java.awt.Color(255, 255, 255));
        letra57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra57.setText("A");
        letra57.setAutoscrolls(true);
        letra57.setMaximumSize(new java.awt.Dimension(50, 50));
        letra57.setMinimumSize(new java.awt.Dimension(50, 50));
        letra57.setOpaque(true);
        letra57.setPreferredSize(new java.awt.Dimension(50, 50));
        letra57.setSize(new java.awt.Dimension(65, 46));
        add(letra57);

        letra58.setBackground(new java.awt.Color(255, 255, 255));
        letra58.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra58.setForeground(new java.awt.Color(255, 255, 255));
        letra58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra58.setText("A");
        letra58.setAutoscrolls(true);
        letra58.setMaximumSize(new java.awt.Dimension(50, 50));
        letra58.setMinimumSize(new java.awt.Dimension(50, 50));
        letra58.setOpaque(true);
        letra58.setPreferredSize(new java.awt.Dimension(50, 50));
        letra58.setSize(new java.awt.Dimension(65, 46));
        add(letra58);

        letra59.setBackground(new java.awt.Color(255, 255, 255));
        letra59.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra59.setForeground(new java.awt.Color(255, 255, 255));
        letra59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra59.setText("A");
        letra59.setAutoscrolls(true);
        letra59.setMaximumSize(new java.awt.Dimension(50, 50));
        letra59.setMinimumSize(new java.awt.Dimension(50, 50));
        letra59.setOpaque(true);
        letra59.setPreferredSize(new java.awt.Dimension(50, 50));
        letra59.setSize(new java.awt.Dimension(65, 46));
        add(letra59);

        letra60.setBackground(new java.awt.Color(255, 255, 255));
        letra60.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra60.setForeground(new java.awt.Color(255, 255, 255));
        letra60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra60.setText("A");
        letra60.setAutoscrolls(true);
        letra60.setMaximumSize(new java.awt.Dimension(50, 50));
        letra60.setMinimumSize(new java.awt.Dimension(50, 50));
        letra60.setOpaque(true);
        letra60.setPreferredSize(new java.awt.Dimension(50, 50));
        letra60.setSize(new java.awt.Dimension(65, 46));
        add(letra60);

        letra61.setBackground(new java.awt.Color(255, 255, 255));
        letra61.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra61.setForeground(new java.awt.Color(255, 255, 255));
        letra61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra61.setText("A");
        letra61.setAutoscrolls(true);
        letra61.setMaximumSize(new java.awt.Dimension(50, 50));
        letra61.setMinimumSize(new java.awt.Dimension(50, 50));
        letra61.setOpaque(true);
        letra61.setPreferredSize(new java.awt.Dimension(50, 50));
        letra61.setSize(new java.awt.Dimension(65, 46));
        add(letra61);

        letra62.setBackground(new java.awt.Color(255, 255, 255));
        letra62.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra62.setForeground(new java.awt.Color(255, 255, 255));
        letra62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra62.setText("A");
        letra62.setAutoscrolls(true);
        letra62.setMaximumSize(new java.awt.Dimension(50, 50));
        letra62.setMinimumSize(new java.awt.Dimension(50, 50));
        letra62.setOpaque(true);
        letra62.setPreferredSize(new java.awt.Dimension(50, 50));
        letra62.setSize(new java.awt.Dimension(65, 46));
        add(letra62);

        letra63.setBackground(new java.awt.Color(255, 255, 255));
        letra63.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra63.setForeground(new java.awt.Color(255, 255, 255));
        letra63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra63.setText("A");
        letra63.setAutoscrolls(true);
        letra63.setMaximumSize(new java.awt.Dimension(50, 50));
        letra63.setMinimumSize(new java.awt.Dimension(50, 50));
        letra63.setOpaque(true);
        letra63.setPreferredSize(new java.awt.Dimension(50, 50));
        letra63.setSize(new java.awt.Dimension(65, 46));
        add(letra63);

        letra64.setBackground(new java.awt.Color(255, 255, 255));
        letra64.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        letra64.setForeground(new java.awt.Color(255, 255, 255));
        letra64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra64.setText("A");
        letra64.setAutoscrolls(true);
        letra64.setMaximumSize(new java.awt.Dimension(50, 50));
        letra64.setMinimumSize(new java.awt.Dimension(50, 50));
        letra64.setOpaque(true);
        letra64.setPreferredSize(new java.awt.Dimension(50, 50));
        letra64.setSize(new java.awt.Dimension(65, 46));
        add(letra64);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel letra01;
    private javax.swing.JLabel letra10;
    private javax.swing.JLabel letra11;
    private javax.swing.JLabel letra12;
    private javax.swing.JLabel letra13;
    private javax.swing.JLabel letra14;
    private javax.swing.JLabel letra15;
    private javax.swing.JLabel letra16;
    private javax.swing.JLabel letra17;
    private javax.swing.JLabel letra18;
    private javax.swing.JLabel letra19;
    private javax.swing.JLabel letra2;
    private javax.swing.JLabel letra20;
    private javax.swing.JLabel letra21;
    private javax.swing.JLabel letra22;
    private javax.swing.JLabel letra23;
    private javax.swing.JLabel letra24;
    private javax.swing.JLabel letra25;
    private javax.swing.JLabel letra26;
    private javax.swing.JLabel letra27;
    private javax.swing.JLabel letra28;
    private javax.swing.JLabel letra29;
    private javax.swing.JLabel letra3;
    private javax.swing.JLabel letra30;
    private javax.swing.JLabel letra31;
    private javax.swing.JLabel letra32;
    private javax.swing.JLabel letra33;
    private javax.swing.JLabel letra34;
    private javax.swing.JLabel letra35;
    private javax.swing.JLabel letra36;
    private javax.swing.JLabel letra37;
    private javax.swing.JLabel letra38;
    private javax.swing.JLabel letra39;
    private javax.swing.JLabel letra4;
    private javax.swing.JLabel letra40;
    private javax.swing.JLabel letra41;
    private javax.swing.JLabel letra42;
    private javax.swing.JLabel letra43;
    private javax.swing.JLabel letra44;
    private javax.swing.JLabel letra45;
    private javax.swing.JLabel letra46;
    private javax.swing.JLabel letra47;
    private javax.swing.JLabel letra48;
    private javax.swing.JLabel letra49;
    private javax.swing.JLabel letra5;
    private javax.swing.JLabel letra50;
    private javax.swing.JLabel letra51;
    private javax.swing.JLabel letra52;
    private javax.swing.JLabel letra53;
    private javax.swing.JLabel letra54;
    private javax.swing.JLabel letra55;
    private javax.swing.JLabel letra56;
    private javax.swing.JLabel letra57;
    private javax.swing.JLabel letra58;
    private javax.swing.JLabel letra59;
    private javax.swing.JLabel letra6;
    private javax.swing.JLabel letra60;
    private javax.swing.JLabel letra61;
    private javax.swing.JLabel letra62;
    private javax.swing.JLabel letra63;
    private javax.swing.JLabel letra64;
    private javax.swing.JLabel letra7;
    private javax.swing.JLabel letra8;
    private javax.swing.JLabel letra9;
    // End of variables declaration//GEN-END:variables
}
