/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toy.anagrams.ui;

/**
 *
 * @author Roland
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scorePanel = new javax.swing.JPanel();
        lbMyScore = new javax.swing.JLabel();
        lbVersusSymbol = new javax.swing.JLabel();
        lbOpponentScore = new javax.swing.JLabel();
        centralPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbDice1 = new javax.swing.JLabel();
        lbPlusSymbol = new javax.swing.JLabel();
        lbDice2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        chatPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChatConsole = new javax.swing.JTextArea();
        tfChatInput = new javax.swing.JTextField();
        btSendMessage = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 800));
        setMinimumSize(new java.awt.Dimension(128, 800));
        setPreferredSize(new java.awt.Dimension(350, 800));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        scorePanel.setBackground(new java.awt.Color(149, 165, 166));
        scorePanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        scorePanel.setPreferredSize(new java.awt.Dimension(350, 50));

        lbMyScore.setBackground(new java.awt.Color(127, 140, 141));
        lbMyScore.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbMyScore.setForeground(new java.awt.Color(255, 255, 255));
        lbMyScore.setText("64");
        lbMyScore.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lbMyScore.setOpaque(true);
        scorePanel.add(lbMyScore);

        lbVersusSymbol.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbVersusSymbol.setForeground(new java.awt.Color(255, 255, 255));
        lbVersusSymbol.setText("x");
        scorePanel.add(lbVersusSymbol);

        lbOpponentScore.setBackground(new java.awt.Color(127, 140, 141));
        lbOpponentScore.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbOpponentScore.setForeground(new java.awt.Color(255, 255, 255));
        lbOpponentScore.setText("64");
        lbOpponentScore.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lbOpponentScore.setOpaque(true);
        scorePanel.add(lbOpponentScore);

        add(scorePanel);

        centralPanel.setBackground(new java.awt.Color(236, 240, 241));
        centralPanel.setPreferredSize(new java.awt.Dimension(350, 350));
        centralPanel.setRequestFocusEnabled(false);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        lbDice1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbDice1.setForeground(new java.awt.Color(255, 255, 255));
        lbDice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDice1.setText("6");
        lbDice1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbDice1);

        lbPlusSymbol.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbPlusSymbol.setForeground(new java.awt.Color(255, 255, 255));
        lbPlusSymbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlusSymbol.setText("+");
        lbPlusSymbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbPlusSymbol);

        lbDice2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbDice2.setForeground(new java.awt.Color(255, 255, 255));
        lbDice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDice2.setText("6");
        lbDice2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbDice2);

        jPanel2.add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(230, 126, 34));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 5, 1));

        jLabel1.setBackground(new java.awt.Color(230, 126, 34));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("movimentos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3);

        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("PALAVRA CINCO");
        jTextField2.setMinimumSize(new java.awt.Dimension(340, 26));
        jTextField2.setName("tfWordGuess"); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(340, 60));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centralPanelLayout = new javax.swing.GroupLayout(centralPanel);
        centralPanel.setLayout(centralPanelLayout);
        centralPanelLayout.setHorizontalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centralPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(centralPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centralPanelLayout.setVerticalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centralPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        add(centralPanel);

        chatPanel.setBackground(new java.awt.Color(184, 203, 205));

        taChatConsole.setColumns(20);
        taChatConsole.setRows(5);
        taChatConsole.setText("Eventos e mensagens aparecerão aqui!");
        jScrollPane1.setViewportView(taChatConsole);

        tfChatInput.setText("enviar mensagem...");
        tfChatInput.setName("tfChatInput"); // NOI18N
        tfChatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChatInputActionPerformed(evt);
            }
        });

        btSendMessage.setText("jButton1");
        btSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfChatInput)
                .addContainerGap())
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(chatPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void btSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSendMessageActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tfChatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChatInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSendMessage;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbDice1;
    private javax.swing.JLabel lbDice2;
    private javax.swing.JLabel lbMyScore;
    private javax.swing.JLabel lbOpponentScore;
    private javax.swing.JLabel lbPlusSymbol;
    private javax.swing.JLabel lbVersusSymbol;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JTextArea taChatConsole;
    private javax.swing.JTextField tfChatInput;
    // End of variables declaration//GEN-END:variables
}
