/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.viraletras.view;

/**
 *
 * @author Roland
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scorePanel = new javax.swing.JPanel();
        lbMyScore = new javax.swing.JLabel();
        lbVersusSymbol = new javax.swing.JLabel();
        lbOpponentScore = new javax.swing.JLabel();
        centralPanel = new javax.swing.JPanel();
        dicesContainerPanel = new javax.swing.JPanel();
        diceNumbersPanel = new javax.swing.JPanel();
        lbDice1 = new javax.swing.JLabel();
        lbPlusSymbol = new javax.swing.JLabel();
        lbDice2 = new javax.swing.JLabel();
        movesLabelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfWordGuess = new javax.swing.JTextField();
        btConfirmWord = new javax.swing.JButton();
        btRejectWord = new javax.swing.JButton();
        chatPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChatConsole = new javax.swing.JTextArea();
        tfChatInput = new javax.swing.JTextField();
        btSendMessage = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 700));
        setMinimumSize(new java.awt.Dimension(350, 600));
        setPreferredSize(new java.awt.Dimension(350, 650));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        scorePanel.setBackground(new java.awt.Color(149, 165, 166));
        scorePanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        scorePanel.setMinimumSize(new java.awt.Dimension(350, 50));
        scorePanel.setPreferredSize(new java.awt.Dimension(350, 50));

        lbMyScore.setBackground(new java.awt.Color(127, 140, 141));
        lbMyScore.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbMyScore.setForeground(new java.awt.Color(255, 255, 255));
        lbMyScore.setText("64");
        lbMyScore.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lbMyScore.setOpaque(true);
        scorePanel.add(lbMyScore);

        lbVersusSymbol.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbVersusSymbol.setForeground(new java.awt.Color(255, 255, 255));
        lbVersusSymbol.setText("x");
        scorePanel.add(lbVersusSymbol);

        lbOpponentScore.setBackground(new java.awt.Color(127, 140, 141));
        lbOpponentScore.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbOpponentScore.setForeground(new java.awt.Color(255, 255, 255));
        lbOpponentScore.setText("64");
        lbOpponentScore.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lbOpponentScore.setOpaque(true);
        scorePanel.add(lbOpponentScore);

        add(scorePanel);

        centralPanel.setBackground(new java.awt.Color(236, 240, 241));
        centralPanel.setMinimumSize(new java.awt.Dimension(350, 320));
        centralPanel.setRequestFocusEnabled(false);
        centralPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        dicesContainerPanel.setLayout(new javax.swing.BoxLayout(dicesContainerPanel, javax.swing.BoxLayout.Y_AXIS));

        diceNumbersPanel.setBackground(new java.awt.Color(243, 156, 18));
        diceNumbersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        diceNumbersPanel.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        lbDice1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbDice1.setForeground(new java.awt.Color(255, 255, 255));
        lbDice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDice1.setText("6");
        lbDice1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        diceNumbersPanel.add(lbDice1);

        lbPlusSymbol.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbPlusSymbol.setForeground(new java.awt.Color(255, 255, 255));
        lbPlusSymbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlusSymbol.setText("+");
        lbPlusSymbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        diceNumbersPanel.add(lbPlusSymbol);

        lbDice2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbDice2.setForeground(new java.awt.Color(255, 255, 255));
        lbDice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDice2.setText("6");
        lbDice2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        diceNumbersPanel.add(lbDice2);

        dicesContainerPanel.add(diceNumbersPanel);

        movesLabelPanel.setBackground(new java.awt.Color(230, 126, 34));
        movesLabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 5, 1));

        jLabel1.setBackground(new java.awt.Color(230, 126, 34));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("movimentos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout movesLabelPanelLayout = new javax.swing.GroupLayout(movesLabelPanel);
        movesLabelPanel.setLayout(movesLabelPanelLayout);
        movesLabelPanelLayout.setHorizontalGroup(
            movesLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(movesLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movesLabelPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        movesLabelPanelLayout.setVerticalGroup(
            movesLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(movesLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movesLabelPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dicesContainerPanel.add(movesLabelPanel);

        centralPanel.add(dicesContainerPanel);

        tfWordGuess.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        tfWordGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfWordGuess.setText("PALAVRA CINCO");
        tfWordGuess.setMinimumSize(new java.awt.Dimension(340, 26));
        tfWordGuess.setName("tfWordGuess"); // NOI18N
        tfWordGuess.setPreferredSize(new java.awt.Dimension(340, 60));
        tfWordGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWordGuessActionPerformed(evt);
            }
        });
        centralPanel.add(tfWordGuess);

        btConfirmWord.setBackground(new java.awt.Color(39, 174, 96));
        btConfirmWord.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btConfirmWord.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmWord.setText("Confirmar");
        btConfirmWord.setBorderPainted(false);
        btConfirmWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfirmWord.setFocusCycleRoot(true);
        btConfirmWord.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btConfirmWord.setMaximumSize(new java.awt.Dimension(340, 48));
        btConfirmWord.setMinimumSize(new java.awt.Dimension(340, 48));
        btConfirmWord.setPreferredSize(new java.awt.Dimension(340, 48));
        btConfirmWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmWordActionPerformed(evt);
            }
        });
        centralPanel.add(btConfirmWord);

        btRejectWord.setBackground(new java.awt.Color(192, 57, 43));
        btRejectWord.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btRejectWord.setForeground(new java.awt.Color(255, 255, 255));
        btRejectWord.setText("Rejeitar");
        btRejectWord.setBorderPainted(false);
        btRejectWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRejectWord.setFocusCycleRoot(true);
        btRejectWord.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btRejectWord.setMaximumSize(new java.awt.Dimension(340, 48));
        btRejectWord.setMinimumSize(new java.awt.Dimension(340, 48));
        btRejectWord.setPreferredSize(new java.awt.Dimension(340, 48));
        btRejectWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRejectWordActionPerformed(evt);
            }
        });
        centralPanel.add(btRejectWord);

        add(centralPanel);

        chatPanel.setBackground(new java.awt.Color(184, 203, 205));
        chatPanel.setMaximumSize(new java.awt.Dimension(32767, 340));
        chatPanel.setLayout(new javax.swing.BoxLayout(chatPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        taChatConsole.setEditable(false);
        taChatConsole.setLineWrap(true);
        taChatConsole.setRows(15);
        taChatConsole.setText("Eventos e mensagens aparecerão aqui!");
        taChatConsole.setMaximumSize(new java.awt.Dimension(500, 32767));
        taChatConsole.setMinimumSize(new java.awt.Dimension(350, 330));
        jScrollPane1.setViewportView(taChatConsole);

        chatPanel.add(jScrollPane1);

        tfChatInput.setText("digite a mensagem...");
        tfChatInput.setName("tfChatInput"); // NOI18N
        tfChatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChatInputActionPerformed(evt);
            }
        });
        chatPanel.add(tfChatInput);

        btSendMessage.setBackground(new java.awt.Color(52, 152, 219));
        btSendMessage.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btSendMessage.setForeground(new java.awt.Color(255, 255, 255));
        btSendMessage.setText("Enviar");
        btSendMessage.setAlignmentX(0.5F);
        btSendMessage.setBorderPainted(false);
        btSendMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSendMessage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btSendMessage.setMaximumSize(new java.awt.Dimension(1000, 29));
        btSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendMessageActionPerformed(evt);
            }
        });
        chatPanel.add(btSendMessage);

        add(chatPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void tfWordGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWordGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWordGuessActionPerformed

    private void btConfirmWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmWordActionPerformed

    private void btRejectWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRejectWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRejectWordActionPerformed

    private void btSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendMessageActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btSendMessageActionPerformed

    private void tfChatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChatInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmWord;
    private javax.swing.JButton btRejectWord;
    private javax.swing.JButton btSendMessage;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JPanel diceNumbersPanel;
    private javax.swing.JPanel dicesContainerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDice1;
    private javax.swing.JLabel lbDice2;
    private javax.swing.JLabel lbMyScore;
    private javax.swing.JLabel lbOpponentScore;
    private javax.swing.JLabel lbPlusSymbol;
    private javax.swing.JLabel lbVersusSymbol;
    private javax.swing.JPanel movesLabelPanel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JTextArea taChatConsole;
    private javax.swing.JTextField tfChatInput;
    private javax.swing.JTextField tfWordGuess;
    // End of variables declaration//GEN-END:variables
}
